include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    unnecessary_cast: ignore
    prefer_const_declarations: ignore
