// File generated by flutterfire_cli.
// Ignore this file as it will be replaced when you run flutterfire config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFNmUDrt5H0G8S5hyrDVvQfobVWbR6mkI',
    appId: '1:561314373498:web:poafix-web-app',
    messagingSenderId: '561314373498',
    projectId: 'poafix',
    authDomain: 'poafix.firebaseapp.com',
    storageBucket: 'poafix.firebasestorage.app',
    measurementId: 'G-PLACEHOLDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFNmUDrt5H0G8S5hyrDVvQfobVWbR6mkI',
    appId: '1:561314373498:android:1822379f2a2f7aaf7fc0c3',
    messagingSenderId: '561314373498',
    projectId: 'poafix',
    storageBucket: 'poafix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNmUDrt5H0G8S5hyrDVvQfobVWbR6mkI',
    appId: '1:561314373498:ios:poafix-ios-app',
    messagingSenderId: '561314373498',
    projectId: 'poafix',
    storageBucket: 'poafix.firebasestorage.app',
    iosBundleId: 'com.example.poafix',
  );
}
